from bouquin.db import DBManager
from bouquin.flow_layout import FlowLayout
from bouquin.markdown_editor import MarkdownEditor
from bouquin.markdown_highlighter import MarkdownHighlighter
from bouquin.statistics_dialog import DateHeatMap

DBManager.row_factory

DateHeatMap.minimumSizeHint

FlowLayout.itemAt
FlowLayout.expandingDirections
FlowLayout.hasHeightForWidth
FlowLayout.heightForWidth

MarkdownEditor.apply_weight
MarkdownEditor.apply_italic
MarkdownEditor.apply_strikethrough
MarkdownEditor.apply_code
MarkdownEditor.apply_heading
MarkdownEditor.toggle_bullets
MarkdownEditor.toggle_numbers
MarkdownEditor.toggle_checkboxes

MarkdownHighlighter.highlightBlock
