name: Lint

on:
  push:

jobs:
  test:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            black pyflakes3 vulture

      - name: Run linters
        run: |
          black --diff --check bouquin/*
          black --diff --check tests/*
          pyflakes3 bouquin/*
          pyflakes3 tests/*
          vulture
