name: Trivy

on:
  schedule:
    - cron: '0 1 * * *'
  push:

jobs:
  test:
    runs-on: docker

    container:
      - aquasec/trivy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy scanner
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
          limit-severity: 'CRITICAL'        
